  export const userRows = [{
          id: 1,
          username: "Kim Namjoon",
          avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          email: "namjoon@gmail.com",
          status: "online",
          transaction: "$320.00",
      },
      {
          id: 2,
          username: "Kim Seokjin",
          avatar: "https://i.pinimg.com/564x/61/34/b4/6134b42b48394ab12a22f5cccde2468e.jpg",
          email: "jinwwh@gmail.com",
          status: "offline",
          transaction: "$555.00",
      },
      {
          id: 3,
          username: "Kim Jun Myeon",
          avatar: "https://www.thefamouspeople.com/profiles/images/suho-1.jpg",
          email: "kjmyeon@gmail.com",
          status: "online",
          transaction: "$554.00",
      },
      {
          id: 4,
          username: "Park Chanyeol",
          avatar: "https://thumb.viva.co.id/media/frontend/thumbs3/2018/04/25/5ae050ffc048a-chanyeol-exo_1265_711.jpg",
          email: "chypark@gmail.com",
          status: "online",
          transaction: "$250.00",
      },
      {
          id: 5,
          username: "Kim Min Seok",
          avatar: "https://assets.pikiran-rakyat.com/crop/0x0:0x0/x/photo/2021/08/05/610945998.jpg",
          email: "xiumin@gmail.com",
          status: "offline",
          transaction: "$120.00",
      },
      {
          id: 6,
          username: "Kim Woo Bin",
          avatar: "https://assets.pikiran-rakyat.com/crop/0x0:1080x786/x/photo/2022/02/23/1849742573.jpg",
          email: "binwoo@gmail.com",
          status: "offline",
          transaction: "$605.00",
      },
      {
          id: 7,
          username: "Hwang In Yeop",
          avatar: "https://asianwiki.com/images/e/e9/Hwang_In-Yeop-1991-p1.jpg",
          email: "inyeop@gmail.com",
          status: "offline",
          transaction: "$310.00",
      },
      {
          id: 8,
          username: "Park Hyung Sik",
          avatar: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Park_Hyung-sik_in_Hwarang_Promotion_in_January_2017_02.png",
          email: "phs@gmail.com",
          status: "online",
          transaction: "$543.00",
      },
      {
          id: 9,
          username: "Han Hyo Joo",
          avatar: "https://i.mydramalist.com/BoB0z_5f.jpg",
          email: "hyuujoo@gmail.com",
          status: "online",
          transaction: "$367.00",
      },
      {
          id: 10,
          username: "Lee Ji Eun",
          avatar: "https://i.scdn.co/image/ab6761610000e5eb006ff3c0136a71bfb9928d34",
          email: "IU@gmail.com",
          status: "offline",
          transaction: "$336.00",
      },
  ];

  export const productRows = [{
          id: 1,
          name: "Asus VivoBook Flip TP401MA",
          img: "https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/6/30/1d622262-3657-4488-9282-26155eebc9e2.jpg",
          stock: 500,
          status: "available",
          price: "$552.00",
      },
      {
          id: 2,
          name: "Huper JS 10",
          img: "https://id-test-11.slatic.net/p/59817a1e09eee3681ea586f229c503cc.jpg",
          stock: 0,
          status: "empty",
          price: "$414.00",
      },
      {
          id: 3,
          name: "Apple Airpods",
          img: "https://id-test-11.slatic.net/p/e4e19eb1bb33710ef4b34e4b33daa904.jpg",
          stock: 1000,
          status: "available",
          price: "$130.00",
      },
      {
          id: 4,
          name: "Macbook Pro 13 Inch",
          img: "https://a.ipricegroup.com/media/mithapermata/Macbook_Pro_13_Inch_2020.png",
          stock: 321,
          status: "available",
          price: "$2.242.00",
      },
      {
          id: 5,
          name: "Xiao Mi Pad 6",
          img: "https://phoneaqua.com/products/Xiaomi%20Mi%20Pad%206.jpg",
          stock: 0,
          status: "empty",
          price: "$75.00",
      },
      {
          id: 6,
          name: "Iphone XR",
          img: "https://images.bisnis-cdn.com/posts/2021/08/27/1434759/iphone-xr-merah-dan-kuning.jpg",
          stock: 123,
          status: "available",
          price: "$621.00",
      },
      {
          id: 7,
          name: "Samsung Galaxy Z Flip 3 ",
          img: "https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/8/24/053a75a2-f3fa-40d7-9047-fbe2a3bf160b.jpg",
          stock: 444,
          status: "available",
          price: "$1.055.00",
      },
      {
          id: 8,
          name: "Oppo Find X",
          img: "http://p-id.ipricegroup.com/uploaded_64592b5243c0affe87c598e23047b85a.jpg",
          stock: 601,
          status: "available",
          price: "$483.00",
      },
      {
          id: 9,
          name: "Printer Epson l3110",
          img: "http://static.bmdstatic.com/pk/product/large/5ba9de53578b3.jpg",
          stock: 0,
          status: "empty",
          price: "$138.00",
      },
      {
          id: 10,
          name: "JETEX P1",
          img: "https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/3/25/6f0a5984-a90f-410b-a655-4dc06035cd6a.jpg",
          stock: 880,
          status: "available",
          price: "$120.00",
      },
  ];